# Generated by Django 3.2.4 on 2021-06-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210629_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmongo',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personmongo',
            name='school',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personmongo',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
