# Generated by Django 3.2.4 on 2021-06-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210629_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonMongo',
        ),
        migrations.DeleteModel(
            name='PersonPostgresql',
        ),
    ]
