# Generated by Django 3.2.4 on 2021-06-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_personpostgresql'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonPostgresql',
        ),
    ]
