version: '3.1'

volumes:
  init-db:
  data-db:

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./init-db:/opt/db2
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
